language: python

python: 3.6

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds

install:
  - "pip install -U pip"
  - "pip install unidecode"
  - "pip install git+https://github.com/lektor/lektor#egg=Lektor"

script: "lektor build"

deploy:
  - provider: script
    script: "lektor deploy develop"
    on:
       branch: develop
  - provider: script
    script: "lektor deploy production"
    on:
       branch: production
